services:
  pbi_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pbi_web
    ports:
      - "3010:80"
    restart: always
    environment:
      - NODE_ENV=production
